export type Exercise={name:string;sets:number;reps:string;rest:string;note:string}; type Day={id:number;name:string;focus:string;exercises:Exercise[]}; type Member={id:number;name:string}; type Entry={id:number;memberId:number;dayId:number;exercise:string;weight:number|null;reps:string;note:string;loggedAt:string};
export const DAYS:Day[]=[
{id:1,name:"Upper 1",focus:"Pecho · Espalda · Hombro · Bíceps · Tríceps",exercises:[
{name:"Press plano en máquina",sets:2,reps:"8–10",rest:"3–5 min",note:"También Smith, barra libre o cualquier press plano sobrecargable."},{name:"Press inclinado bajo con mancuernas",sets:2,reps:"10–12",rest:"3–5 min",note:"Inclinación 15–30°. También máquina o Smith inclinado."},{name:"T-bar row",sets:2,reps:"10–12",rest:"3–5 min",note:"Codos abiertos. También remo con pecho apoyado, mancuernas o cable."},{name:"Curl de bíceps standaway",sets:3,reps:"10–12",rest:"2–4 min",note:"Codos detrás del cuerpo (bayesian); puede ser unilateral."},{name:"Extensión de tríceps cruzada unilateral",sets:3,reps:"10–12",rest:"2–4 min",note:"Con cuff en cable."},{name:"Vuelo lateral acostado con cables",sets:3,reps:"10–12",rest:"2–4 min",note:"Con cuffs; también sirve cualquier vuelo lateral."}]},
{id:2,name:"Lower",focus:"Isquiotibiales · Cuádriceps · Glúteo · Pantorrilla · Hombro",exercises:[
{name:"Cable crunch",sets:2,reps:"10–12",rest:"1–2 min",note:"Superset con plancha lateral; comienza activando el core."},{name:"Plancha lateral",sets:2,reps:"segundos",rest:"1–2 min",note:"Registra los segundos para progresar."},{name:"Leg curl sentado",sets:2,reps:"10–12",rest:"2–4 min",note:"También leg curl acostado."},{name:"Hack squat",sets:2,reps:"8–10",rest:"3–5 min",note:"También péndulo, sentadilla Smith o barra libre high bar."},{name:"Prensa unilateral",sets:2,reps:"10–12",rest:"3–5 min",note:"También sentadilla búlgara."},{name:"Calf raise en prensa",sets:3,reps:"10–12",rest:"2–4 min",note:"Puede ser cualquier calf raise."},{name:"Vuelo lateral unilateral",sets:3,reps:"10–12",rest:"2–4 min",note:"Cable + cuff."}]},
{id:4,name:"Upper 2",focus:"Espalda · Pecho · Hombro · Bíceps · Tríceps · Core",exercises:[
{name:"Leg raises",sets:2,reps:"10–12",rest:"1–2 min",note:"Superset con plancha; comienza con abdomen."},{name:"Plancha",sets:2,reps:"segundos",rest:"1–2 min",note:"Registra los segundos."},{name:"Pulldown bilateral",sets:2,reps:"10–12",rest:"3–5 min",note:"Codos abiertos; también pull-ups u otro pulldown."},{name:"Remo dorsal unilateral",sets:2,reps:"12–14",rest:"3–5 min",note:"En máquina o con mancuerna."},{name:"Press inclinado bajo en Smith",sets:2,reps:"8–10",rest:"3–5 min",note:"15° de inclinación; también barra libre microprogresable."},{name:"Curl predicador unilateral",sets:3,reps:"10–12",rest:"2–4 min",note:"Máquina o mancuerna."},{name:"Extensión de tríceps sobre la cabeza",sets:3,reps:"10–12",rest:"2–4 min",note:"Con cuff o cualquier extensión overhead."},{name:"Vuelo crucifix hombro posterior",sets:3,reps:"10–12",rest:"2–4 min",note:"Con cuff en cable."}]},
{id:6,name:"Full Body",focus:"Cadena posterior · Cuádriceps · Espalda · Pecho · Brazos",exercises:[
{name:"RDL",sets:2,reps:"8–10",rest:"3–5 min",note:"También hiperextensión, buenos días o hip thrust."},{name:"Prensa",sets:2,reps:"10–12",rest:"2–4 min",note:"Pies altos para más glúteo e isquiotibiales."},{name:"Remo pecho apoyado con mancuernas",sets:2,reps:"12–14",rest:"3–5 min",note:"También T-bar, máquina o cables."},{name:"Pulldown dorsal unilateral",sets:2,reps:"10–12",rest:"3–5 min",note:"Foco dorsal y trabajo unilateral."},{name:"Press plano en Smith",sets:2,reps:"8–10",rest:"3–5 min",note:"Press plano que permite microprogresiones."},{name:"Extensión de tríceps doble cuerda",sets:3,reps:"10–12",rest:"2–4 min",note:"Codos hacia abajo; cualquier extensión válida."},{name:"Curl bíceps unilateral mancuerna",sets:3,reps:"10–12",rest:"2–4 min",note:"Controla la fase excéntrica."}]}];

